### ISSUE TITLE
Questions about proper training epoch

### ISSUE THREAD

**Issue by YJ-142150** [VITA-Group/GNT#10]
Hi, thanks for nice work!
I trained GNT for 50k~100k epochs without using pretrained model. But the results didn't seemed to be good as pretrained ones. Is there recommended training epochs? And does N_rand affects the performance? The config that I changed was N_rand because of lack of CUDA. 
Thanks for any assistance.

**Comment by MukundVarmaT** [comment]
Hi @YJ-142150 
Thank you for your interest in our work! I think the configs on the repo are a bit outdated (apologies for that, I will fix that immediately), N_samples must be 192 and we trained for a total of 512 x 8 rays (N_rand) per iteration. I don't think N_rand matters as much if you train for longer but the N_samples do! 

I hope this helps? Do let us know if you have any other issues.

**Comment by YJ-142150** [comment]
Thanks a lot for your help!
