### ISSUE TITLE
How to apply multi-gpu training?

### ISSUE THREAD

**Issue by lifuguan** [VITA-Group/GNT#13]
Hello, thanks for the great work! I'm wondering how can we apply mulit-gpu training?

I use the following command
```bash
python train.py --config configs/gnt_ft_rffr.txt --distributed --local_rank 2
```
but it occurs the following problems:
```bash
Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```

The distributed training code of `train.py` is shown below:
```python
    if args.distributed:
        torch.distributed.init_process_group(backend="nccl", init_method="env://localhost:50000")
        args.local_rank = int(os.environ.get("LOCAL_RANK"))
        torch.cuda.set_device(args.local_rank)
```

**Comment by MukundVarmaT** [comment]
Hi, 

Thank you for your interest in our work! To train on multiple GPUs, 

`python3 -m torch.distributed.launch --nnodes=1 --node_rank=0 --nproc_per_node=<num-gpus> --use_env --master_port=21221 train.py  ... (remaining args)`

**Comment by lifuguan** [comment]
Thanks! One more question following the [issue](https://github.com/VITA-Group/GNT/issues/10#issuecomment-1373816692), if I train the model with 8 gpus, should I change `N_rand` from 4096 to 512?

**Comment by MukundVarmaT** [comment]
Yes, thats correct!
