### ISSUE TITLE
About Cross-scene Training Setting

### ISSUE THREAD

**Issue by YouyuChen0207** [VITA-Group/GNT#22]
Thanks for you attention. You provided training command as `python3 train.py --config configs/gnt_full.txt` without other arguments, but I find the default number of ray sampling is 512 in `config.py`, while your paper said this number is 4096 which is 8 times of default setting. Dose it mean you trained you model with 8 gpu?

**Comment by MukundVarmaT** [comment]
Yes that is correct.

**Comment by YouyuChen0207** [comment]
I see. Thank you!
