### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by CCOSerika** [VITA-Group/GNT#3]
Hi, author. Thanx for your great work!
I cannot wait to see how it will work. I train on my RTX3090 but it gives "cuda out of memory".
Could u kindly provide the trained ckpts with us to check? Or how can I set the parameters to run it successfully.
Looking forward to your reply!

**Comment by CCOSerika** [comment]
By the way, what graphics card are u use for training? Will RTX3090 be okey?

**Comment by CCOSerika** [comment]
By the way, what graphics card did u use for training? Will RTX3090 be okey?

**Comment by MukundVarmaT** [comment]
Thank you for your interest in our work. We have released the pre-trained models [here](https://github.com/VITA-Group/GNT#pre-trained-models).  We run all our experiments on RTX A6000 cards (with 48G memory). You could try reducing the `N_rand` parameter to train the model on smaller cards.

**Comment by CCOSerika** [comment]
I got it. Thank you so much for your reply. I'll try it.

**Comment by CCOSerika** [comment]
I got it. Thank you so much for your reply. I'll try it.
